export type DemoRole = 'booking' | 'estimate' | 'ops'

export interface DemoFeatureMeta {
  role: DemoRole
  features: string[]
}

/** Sales showroom metadata keyed by demo route path — full capability lists for mix-and-match. */
export const DEMO_FEATURES: Record<string, DemoFeatureMeta> = {
  '/venue/harbourbook': {
    role: 'booking',
    features: [
      'Floor plan rooms',
      'Day rail',
      'Occupancy strip',
      'Time rail',
      'Party stepper',
      'Extras chips',
      'Setup checklist',
      'Recurring toggle',
      'Live estimate',
      'Demo mode',
    ],
  },
  '/venue/hallboard': {
    role: 'ops',
    features: [
      'KPI header',
      'Coverage banner',
      'Rooms × hours grid',
      'Turnaround buffer',
      'Status cycle',
      'Staff assignee',
      'Free-slot coverage',
      'Demo mode',
    ],
  },
  '/beekeeping/hiverun': {
    role: 'ops',
    features: [
      'Cluster map',
      'Phone shell',
      'FAB log action',
      'My roster tab',
      'Assigned banner',
      'Micro meters',
      'Landowner card',
      'Hive break chips',
      'Task filter',
      'Treatment checklist',
      'Yard flag',
      'Demo mode',
    ],
  },
  '/beekeeping/apiary': {
    role: 'ops',
    features: [
      'KPI header',
      'Admin tabs',
      'Week calendar nav',
      'Yard filter chips',
      'Roster grid',
      'Staff role assign',
      'Visit sequence',
      'Staff load',
      'Cluster map',
      'Bulk assign',
      'Season rules',
      'Demo mode',
    ],
  },
  '/homecare/visit': {
    role: 'ops',
    features: [
      'Household map',
      'Phone shell',
      'Today tab',
      'Assigned banner',
      'Client cards',
      'Meds due',
      'Grouped tasks',
      'Visit length',
      'Concern flag',
      'Close-out checklist',
      'Family hand-off',
    ],
  },
  '/homecare/rounds': {
    role: 'ops',
    features: [
      'Admin tabs',
      'Week calendar nav',
      'Uncovered filter',
      'Coverage hero',
      'Carers × hours grid',
      'Staff role assign',
      'Status pipeline',
      'Carer load bars',
      'Client highlight',
      'Suggest carer',
      'Coverage auto-fill',
    ],
  },
  '/fitness/studioflow': {
    role: 'booking',
    features: [
      'Credit wallet',
      'Wizard steps',
      'Class caps',
      'Almost-full cue',
      'Waitlist join',
      'Prepaid plans',
      'Sync chips',
      'Peak day data',
      'Demo mode',
    ],
  },
  '/fitness/classboard': {
    role: 'ops',
    features: [
      'Fill bars',
      'Fill urgency',
      'Substitute instructor',
      'Attendee roster',
      'Class cap',
      'Exercise catalog',
      'Equipment checklist',
      'Sync chips',
      'Demo mode',
    ],
  },
  '/riding/shoreride': {
    role: 'booking',
    features: [
      'Tide window strip',
      'Wizard steps',
      'Ride type cards',
      'Tide/sun windows',
      'Horse picker',
      'Stay add-on',
      'Waiver gate',
      'Weight chips',
      'Experience chips',
      'Safety checklist',
    ],
  },
  '/riding/yardboard': {
    role: 'ops',
    features: [
      'Coverage banner',
      'Horse × day grid',
      'Groom assignee',
      'Rest toggles',
      'Max-rides caps',
      'Stay nights',
      'Calendar blocks',
      'Sync chips',
    ],
  },
  '/yacht/coastal': {
    role: 'booking',
    features: [
      'Package wizard',
      'Route chips',
      'Route map',
      'Calendar grid',
      'Weather cues',
      'Party size',
      'Safety briefing',
    ],
  },
  '/yacht/adventure': {
    role: 'ops',
    features: [
      'Route-first map',
      'Mission recap',
      'Day rail',
      'Time rail',
      'Wind/swell gate',
      'Crew roles',
      'Crew stepper',
    ],
  },
  '/taxi/mohua': {
    role: 'booking',
    features: [
      'Phone shell',
      'Saved places',
      'Pickup/drop-off',
      'Passenger chips',
      'Vehicle tiers',
      'Now/later',
      'Peak surcharge',
      'Road-snapped map',
      'Fare breakdown',
    ],
  },
  '/taxi/bayhop': {
    role: 'booking',
    features: [
      'Phase steps',
      'Dispatch queue',
      'Place grid',
      'Road-snapped map',
      'Live estimate',
      'Vehicle cards',
      'Passenger chips',
      'Time slot rail',
      'Peak slots',
    ],
  },
  '/handyman/bayfix': {
    role: 'booking',
    features: [
      'Wizard steps',
      'Trade quick-adds',
      'Multi-trade chips',
      'Live estimate',
      'Day rail',
      'Time rail',
      'Site access card',
      'Photo stub',
      'Demo mode',
    ],
  },
  '/handyman/tradeboard': {
    role: 'estimate',
    features: [
      'Trade quick-adds',
      'Job chips',
      'Kanban columns',
      'Day rail',
      'Time rail',
      'Live estimate',
      'Site area',
      'Demo mode',
    ],
  },
  '/pruning/canopy': {
    role: 'booking',
    features: [
      'Tree catalog',
      'Qty steppers',
      'Hazard flags',
      'Add-ons',
      'Live estimate',
      'Day rail',
      'Time rail',
      'Access notes',
    ],
  },
  '/pruning/orchard': {
    role: 'estimate',
    features: [
      'Zone picker A1–D4',
      'Species tiles',
      'Tile counters',
      'Quick-add chips',
      'Add-ons',
      'Day rail',
      'Time rail',
      'Side estimate',
    ],
  },
  '/painting/freshcoat': {
    role: 'estimate',
    features: [
      'Wizard steps',
      'Surface editor',
      'Add surface kinds',
      'Paint system',
      'Undercoat chips',
      'Live estimate',
      'Prep checklist',
      'Ballpark export',
    ],
  },
  '/painting/paintboard': {
    role: 'estimate',
    features: [
      'Weather window',
      'Cladding profiles',
      'Roof pitch',
      'Paintable area',
      'Paint chips',
      'Undercoat chips',
      'Side estimate',
      'Ballpark export',
    ],
  },
}

export const ROLE_LABELS: Record<DemoRole, string> = {
  booking: 'Booking showcase',
  estimate: 'Estimate showcase',
  ops: 'Ops showcase',
}
