/** Auto-generated by scripts/fetch-hub-images.mjs — do not edit manually. */

export interface SiteImage {
  src: string;
  alt: string;
}

export const imageManifest = {
  "logo": "/images/logo.png",
  "pages": {
    "home": [
      {
        "src": "/images/home/00-favicon.ico",
        "alt": "home image 1"
      },
      {
        "src": "/images/home/01-SLC_gardens_02.png_quot_",
        "alt": "home image 2"
      },
      {
        "src": "/images/home/02-SLC_gardens_02.png",
        "alt": "home image 3"
      },
      {
        "src": "/images/home/03-SLC_gardens_02.png",
        "alt": "home image 4"
      },
      {
        "src": "/images/home/04-NB_making_bricks.jpeg",
        "alt": "home image 5"
      },
      {
        "src": "/images/home/05-NB_making_bricks.jpeg",
        "alt": "home image 6"
      },
      {
        "src": "/images/home/06-IMG20210927122233.jpg",
        "alt": "home image 7"
      },
      {
        "src": "/images/home/07-IMG20210927122233.jpg",
        "alt": "home image 8"
      },
      {
        "src": "/images/home/08-IMG_20240504_143922.jpg",
        "alt": "home image 9"
      },
      {
        "src": "/images/home/09-IMG_20240504_143922.jpg",
        "alt": "home image 10"
      },
      {
        "src": "/images/home/10-IMG_20240504_161256.jpg",
        "alt": "home image 11"
      },
      {
        "src": "/images/home/11-IMG_20240504_161256.jpg",
        "alt": "home image 12"
      },
      {
        "src": "/images/home/12-IMG_20240504_111546.jpg",
        "alt": "home image 13"
      },
      {
        "src": "/images/home/13-IMG_20240504_111546.jpg",
        "alt": "home image 14"
      },
      {
        "src": "/images/home/14-IMG_20240504_104258.jpg",
        "alt": "home image 15"
      },
      {
        "src": "/images/home/15-IMG_20240504_104258.jpg",
        "alt": "home image 16"
      },
      {
        "src": "/images/home/16-2O3A1101_1_.jpg",
        "alt": "home image 17"
      },
      {
        "src": "/images/home/17-2O3A1101_1_.jpg",
        "alt": "home image 18"
      },
      {
        "src": "/images/home/18-IMG_5163.jpeg",
        "alt": "home image 19"
      },
      {
        "src": "/images/home/19-IMG_5163.jpeg",
        "alt": "home image 20"
      },
      {
        "src": "/images/home/20-312892005_5695324130548498_6814575157617456661_n.jpg",
        "alt": "home image 21"
      },
      {
        "src": "/images/home/21-312892005_5695324130548498_6814575157617456661_n.jpg",
        "alt": "home image 22"
      },
      {
        "src": "/images/home/22-316063372_5732244963523081_5966633397324073589_n.jpg",
        "alt": "home image 23"
      },
      {
        "src": "/images/home/23-316063372_5732244963523081_5966633397324073589_n.jpg",
        "alt": "home image 24"
      },
      {
        "src": "/images/home/24-Logo_TDC.png",
        "alt": "home image 25"
      },
      {
        "src": "/images/home/25-Logo_TDC.png",
        "alt": "home image 26"
      },
      {
        "src": "/images/home/26-Sollys_Logo.png",
        "alt": "home image 27"
      },
      {
        "src": "/images/home/27-Sollys_Logo.png",
        "alt": "home image 28"
      },
      {
        "src": "/images/home/28-Logo_Rata_Foundation.png",
        "alt": "home image 29"
      },
      {
        "src": "/images/home/29-Logo_Rata_Foundation.png",
        "alt": "home image 30"
      },
      {
        "src": "/images/home/30-Logo_Sargood.png",
        "alt": "home image 31"
      },
      {
        "src": "/images/home/31-Logo_Sargood.png",
        "alt": "home image 32"
      },
      {
        "src": "/images/home/32-Logo_Pub_Charity.png",
        "alt": "home image 33"
      },
      {
        "src": "/images/home/33-Logo_Pub_Charity.png",
        "alt": "home image 34"
      },
      {
        "src": "/images/home/34-Logo_Tui_Balms.png",
        "alt": "home image 35"
      },
      {
        "src": "/images/home/35-Logo_Tui_Balms.png",
        "alt": "home image 36"
      },
      {
        "src": "/images/home/36-Logo_Network_Tasman.png",
        "alt": "home image 37"
      },
      {
        "src": "/images/home/37-Logo_Network_Tasman.png",
        "alt": "home image 38"
      },
      {
        "src": "/images/home/38-Logo_Fresh_Choice.png",
        "alt": "home image 39"
      },
      {
        "src": "/images/home/39-Logo_Fresh_Choice.png",
        "alt": "home image 40"
      },
      {
        "src": "/images/home/40-Logo_Trash_Palace.png",
        "alt": "home image 41"
      },
      {
        "src": "/images/home/41-Logo_Trash_Palace.png",
        "alt": "home image 42"
      },
      {
        "src": "/images/home/42-Health_Post_Logo.png",
        "alt": "home image 43"
      },
      {
        "src": "/images/home/43-Health_Post_Logo.png",
        "alt": "home image 44"
      },
      {
        "src": "/images/home/44-Mussel_Inn_Logo.png",
        "alt": "home image 45"
      },
      {
        "src": "/images/home/45-Mussel_Inn_Logo.png",
        "alt": "home image 46"
      },
      {
        "src": "/images/home/46-Logo_Nelson_Tasman_Climate_Forum.png",
        "alt": "home image 47"
      },
      {
        "src": "/images/home/47-Logo_Nelson_Tasman_Climate_Forum.png",
        "alt": "home image 48"
      },
      {
        "src": "/images/home/48-Logo_MSD.png",
        "alt": "home image 49"
      },
      {
        "src": "/images/home/49-Logo_MSD.png",
        "alt": "home image 50"
      },
      {
        "src": "/images/home/50-Planetary_Services_Logo",
        "alt": "home image 51"
      },
      {
        "src": "/images/home/51-Planetary_Services_Logo",
        "alt": "home image 52"
      },
      {
        "src": "/images/home/52-Logo_Mohua_Social_Services.png",
        "alt": "home image 53"
      },
      {
        "src": "/images/home/53-Logo_Mohua_Social_Services.png",
        "alt": "home image 54"
      },
      {
        "src": "/images/home/54-Golden_Bay_Community_Trust_Logo.png",
        "alt": "home image 55"
      },
      {
        "src": "/images/home/55-Golden_Bay_Community_Trust_Logo.png",
        "alt": "home image 56"
      },
      {
        "src": "/images/home/56-Top_of_the_South_Logo.png",
        "alt": "home image 57"
      },
      {
        "src": "/images/home/57-Top_of_the_South_Logo.png",
        "alt": "home image 58"
      },
      {
        "src": "/images/home/58-1759124179740",
        "alt": "home image 59"
      },
      {
        "src": "/images/home/59-site.css",
        "alt": "home image 60"
      },
      {
        "src": "/images/home/60-static.css",
        "alt": "home image 61"
      },
      {
        "src": "/images/home/61-site-bundle.81624e0f7f7f25a4ec8743ea63cda189.js",
        "alt": "home image 62"
      }
    ],
    "events": [
      {
        "src": "/images/events/00-favicon.ico",
        "alt": "events image 1"
      },
      {
        "src": "/images/events/01-20250318_161635_Original.jpeg",
        "alt": "events image 2"
      },
      {
        "src": "/images/events/02-20250318_161635_Original.jpeg",
        "alt": "events image 3"
      },
      {
        "src": "/images/events/03-collecting_potatoes",
        "alt": "events image 4"
      },
      {
        "src": "/images/events/04-collecting_potatoes",
        "alt": "events image 5"
      },
      {
        "src": "/images/events/05-Yearly_calendar_circle_in_seasons.png",
        "alt": "events image 6"
      },
      {
        "src": "/images/events/06-Yearly_calendar_circle_in_seasons.png",
        "alt": "events image 7"
      },
      {
        "src": "/images/events/07-20250322_164612_Original.jpeg",
        "alt": "events image 8"
      },
      {
        "src": "/images/events/08-20250322_164612_Original.jpeg",
        "alt": "events image 9"
      },
      {
        "src": "/images/events/09-20250322_165143_Original.jpg",
        "alt": "events image 10"
      },
      {
        "src": "/images/events/10-20250322_165143_Original.jpg",
        "alt": "events image 11"
      },
      {
        "src": "/images/events/11-20250322_165051_Original.jpeg",
        "alt": "events image 12"
      },
      {
        "src": "/images/events/12-20250322_165051_Original.jpeg",
        "alt": "events image 13"
      },
      {
        "src": "/images/events/13-20250322_164635_Original.jpeg",
        "alt": "events image 14"
      },
      {
        "src": "/images/events/14-20250322_164635_Original.jpeg",
        "alt": "events image 15"
      },
      {
        "src": "/images/events/15-20250228_182803_Original.jpeg",
        "alt": "events image 16"
      },
      {
        "src": "/images/events/16-20250228_182803_Original.jpeg",
        "alt": "events image 17"
      },
      {
        "src": "/images/events/17-20250322_172221_Original.jpeg",
        "alt": "events image 18"
      },
      {
        "src": "/images/events/18-20250322_172221_Original.jpeg",
        "alt": "events image 19"
      },
      {
        "src": "/images/events/19-20250322_173826_Original.jpeg",
        "alt": "events image 20"
      },
      {
        "src": "/images/events/20-20250322_173826_Original.jpeg",
        "alt": "events image 21"
      },
      {
        "src": "/images/events/21-20250322_174432_Original.jpeg",
        "alt": "events image 22"
      },
      {
        "src": "/images/events/22-20250322_174432_Original.jpeg",
        "alt": "events image 23"
      },
      {
        "src": "/images/events/23-1759124179740",
        "alt": "events image 24"
      },
      {
        "src": "/images/events/24-site.css",
        "alt": "events image 25"
      },
      {
        "src": "/images/events/25-static.css",
        "alt": "events image 26"
      },
      {
        "src": "/images/events/26-site-bundle.81624e0f7f7f25a4ec8743ea63cda189.js",
        "alt": "events image 27"
      }
    ],
    "courses": [
      {
        "src": "/images/courses/00-favicon.ico",
        "alt": "courses image 1"
      },
      {
        "src": "/images/courses/01-Short_Course-2.png",
        "alt": "courses image 2"
      },
      {
        "src": "/images/courses/02-Short_Course-2.png",
        "alt": "courses image 3"
      },
      {
        "src": "/images/courses/03-2020-10-15_15.30.15.jpg",
        "alt": "courses image 4"
      },
      {
        "src": "/images/courses/04-2020-10-15_15.30.15.jpg",
        "alt": "courses image 5"
      },
      {
        "src": "/images/courses/05-DSCN8341.JPG",
        "alt": "courses image 6"
      },
      {
        "src": "/images/courses/06-DSCN8341.JPG",
        "alt": "courses image 7"
      },
      {
        "src": "/images/courses/07-PHOTO-2023-09-07-11-30-41.jpg",
        "alt": "courses image 8"
      },
      {
        "src": "/images/courses/08-PHOTO-2023-09-07-11-30-41.jpg",
        "alt": "courses image 9"
      },
      {
        "src": "/images/courses/09-Permaculutre_design_2.jpg",
        "alt": "courses image 10"
      },
      {
        "src": "/images/courses/10-Permaculutre_design_2.jpg",
        "alt": "courses image 11"
      },
      {
        "src": "/images/courses/11-2O3A1141.jpg",
        "alt": "courses image 12"
      },
      {
        "src": "/images/courses/12-2O3A1141.jpg",
        "alt": "courses image 13"
      },
      {
        "src": "/images/courses/13-IMG-0567.jpg",
        "alt": "courses image 14"
      },
      {
        "src": "/images/courses/14-IMG-0567.jpg",
        "alt": "courses image 15"
      },
      {
        "src": "/images/courses/15-2020-11-11_11.33.14.jpg",
        "alt": "courses image 16"
      },
      {
        "src": "/images/courses/16-2020-11-11_11.33.14.jpg",
        "alt": "courses image 17"
      },
      {
        "src": "/images/courses/17-2O3A1101_1_.jpg",
        "alt": "courses image 18"
      },
      {
        "src": "/images/courses/18-2O3A1101_1_.jpg",
        "alt": "courses image 19"
      },
      {
        "src": "/images/courses/19-Sustainable_Living_Course.jpg",
        "alt": "courses image 20"
      },
      {
        "src": "/images/courses/20-Sustainable_Living_Course.jpg",
        "alt": "courses image 21"
      },
      {
        "src": "/images/courses/21-DSC_2931.JPG",
        "alt": "courses image 22"
      },
      {
        "src": "/images/courses/22-DSC_2931.JPG",
        "alt": "courses image 23"
      },
      {
        "src": "/images/courses/23-Field_Trip.jpg",
        "alt": "courses image 24"
      },
      {
        "src": "/images/courses/24-Field_Trip.jpg",
        "alt": "courses image 25"
      },
      {
        "src": "/images/courses/25-Sol.jpg",
        "alt": "courses image 26"
      },
      {
        "src": "/images/courses/26-Sol.jpg",
        "alt": "courses image 27"
      },
      {
        "src": "/images/courses/27-Robina.jpg",
        "alt": "courses image 28"
      },
      {
        "src": "/images/courses/28-Robina.jpg",
        "alt": "courses image 29"
      },
      {
        "src": "/images/courses/29-Kerryn.jpg",
        "alt": "courses image 30"
      },
      {
        "src": "/images/courses/30-Kerryn.jpg",
        "alt": "courses image 31"
      },
      {
        "src": "/images/courses/31-Rita.jpg",
        "alt": "courses image 32"
      },
      {
        "src": "/images/courses/32-Rita.jpg",
        "alt": "courses image 33"
      },
      {
        "src": "/images/courses/33-March_2021_Group_Photo.jpg",
        "alt": "courses image 34"
      },
      {
        "src": "/images/courses/34-March_2021_Group_Photo.jpg",
        "alt": "courses image 35"
      },
      {
        "src": "/images/courses/35-WhatsApp_Image_2023-06-04_at_16.16.59.jpeg",
        "alt": "courses image 36"
      },
      {
        "src": "/images/courses/36-WhatsApp_Image_2023-06-04_at_16.16.59.jpeg",
        "alt": "courses image 37"
      },
      {
        "src": "/images/courses/37-Organic_Groiwng.jpg",
        "alt": "courses image 38"
      },
      {
        "src": "/images/courses/38-Organic_Groiwng.jpg",
        "alt": "courses image 39"
      },
      {
        "src": "/images/courses/39-1759124179740",
        "alt": "courses image 40"
      },
      {
        "src": "/images/courses/40-site.css",
        "alt": "courses image 41"
      },
      {
        "src": "/images/courses/41-static.css",
        "alt": "courses image 42"
      },
      {
        "src": "/images/courses/42-site-bundle.81624e0f7f7f25a4ec8743ea63cda189.js",
        "alt": "courses image 43"
      }
    ],
    "education": [
      {
        "src": "/images/education/00-favicon.ico",
        "alt": "education image 1"
      },
      {
        "src": "/images/education/01-IMG20210927122233.jpg",
        "alt": "education image 2"
      },
      {
        "src": "/images/education/02-IMG20210927122233.jpg",
        "alt": "education image 3"
      },
      {
        "src": "/images/education/03-NB_making_bricks.jpeg",
        "alt": "education image 4"
      },
      {
        "src": "/images/education/04-NB_making_bricks.jpeg",
        "alt": "education image 5"
      },
      {
        "src": "/images/education/05-1759124179740",
        "alt": "education image 6"
      },
      {
        "src": "/images/education/06-site.css",
        "alt": "education image 7"
      },
      {
        "src": "/images/education/07-static.css",
        "alt": "education image 8"
      },
      {
        "src": "/images/education/08-site-bundle.81624e0f7f7f25a4ec8743ea63cda189.js",
        "alt": "education image 9"
      }
    ],
    "rentals": [
      {
        "src": "/images/rentals/00-favicon.ico",
        "alt": "rentals image 1"
      },
      {
        "src": "/images/rentals/01-Workshop_space",
        "alt": "rentals image 2"
      },
      {
        "src": "/images/rentals/02-Workshop_space",
        "alt": "rentals image 3"
      },
      {
        "src": "/images/rentals/03-278141901_1016118059008626_3207632928994157992_n.jpg",
        "alt": "rentals image 4"
      },
      {
        "src": "/images/rentals/04-278141901_1016118059008626_3207632928994157992_n.jpg",
        "alt": "rentals image 5"
      },
      {
        "src": "/images/rentals/05-Apple_crusher_image",
        "alt": "rentals image 6"
      },
      {
        "src": "/images/rentals/06-Apple_crusher_image",
        "alt": "rentals image 7"
      },
      {
        "src": "/images/rentals/07-Apple_press.png",
        "alt": "rentals image 8"
      },
      {
        "src": "/images/rentals/08-Apple_press.png",
        "alt": "rentals image 9"
      },
      {
        "src": "/images/rentals/09-permacdesg-1000.jpg",
        "alt": "rentals image 10"
      },
      {
        "src": "/images/rentals/10-permacdesg-1000.jpg",
        "alt": "rentals image 11"
      },
      {
        "src": "/images/rentals/11-5.png",
        "alt": "rentals image 12"
      },
      {
        "src": "/images/rentals/12-5.png",
        "alt": "rentals image 13"
      },
      {
        "src": "/images/rentals/13-1759124179740",
        "alt": "rentals image 14"
      },
      {
        "src": "/images/rentals/14-site.css",
        "alt": "rentals image 15"
      },
      {
        "src": "/images/rentals/15-static.css",
        "alt": "rentals image 16"
      },
      {
        "src": "/images/rentals/16-site-bundle.81624e0f7f7f25a4ec8743ea63cda189.js",
        "alt": "rentals image 17"
      }
    ],
    "compost": [
      {
        "src": "/images/compost/00-favicon.ico",
        "alt": "compost image 1"
      },
      {
        "src": "/images/compost/01-Compost_bin_location_at_the_i-site",
        "alt": "compost image 2"
      },
      {
        "src": "/images/compost/02-Compost_bin_location_at_the_i-site",
        "alt": "compost image 3"
      },
      {
        "src": "/images/compost/03-Compost_bin_location_at_the_SLC",
        "alt": "compost image 4"
      },
      {
        "src": "/images/compost/04-Compost_bin_location_at_the_SLC",
        "alt": "compost image 5"
      },
      {
        "src": "/images/compost/05-Do_s_list.png",
        "alt": "compost image 6"
      },
      {
        "src": "/images/compost/06-Do_s_list.png",
        "alt": "compost image 7"
      },
      {
        "src": "/images/compost/07-Don_t_list.png",
        "alt": "compost image 8"
      },
      {
        "src": "/images/compost/08-Don_t_list.png",
        "alt": "compost image 9"
      },
      {
        "src": "/images/compost/09-Parakai_drop_off_map",
        "alt": "compost image 10"
      },
      {
        "src": "/images/compost/10-Parakai_drop_off_map",
        "alt": "compost image 11"
      },
      {
        "src": "/images/compost/11-Parakai_drop_off_map",
        "alt": "compost image 12"
      },
      {
        "src": "/images/compost/12-Parakai_drop_off_map",
        "alt": "compost image 13"
      },
      {
        "src": "/images/compost/13-Compost_Photo",
        "alt": "compost image 14"
      },
      {
        "src": "/images/compost/14-Compost_Photo",
        "alt": "compost image 15"
      },
      {
        "src": "/images/compost/15-IMG_1310.jpg",
        "alt": "compost image 16"
      },
      {
        "src": "/images/compost/16-IMG_1310.jpg",
        "alt": "compost image 17"
      },
      {
        "src": "/images/compost/17-Compost_Photo",
        "alt": "compost image 18"
      },
      {
        "src": "/images/compost/18-Compost_Photo",
        "alt": "compost image 19"
      },
      {
        "src": "/images/compost/19-Compost_Photo",
        "alt": "compost image 20"
      },
      {
        "src": "/images/compost/20-Compost_Photo",
        "alt": "compost image 21"
      },
      {
        "src": "/images/compost/21-Logo_MSD.png",
        "alt": "compost image 22"
      },
      {
        "src": "/images/compost/22-Logo_MSD.png",
        "alt": "compost image 23"
      },
      {
        "src": "/images/compost/23-TDC_Logo.png",
        "alt": "compost image 24"
      },
      {
        "src": "/images/compost/24-TDC_Logo.png",
        "alt": "compost image 25"
      },
      {
        "src": "/images/compost/25-Logo_Helping_Hands.png",
        "alt": "compost image 26"
      },
      {
        "src": "/images/compost/26-Logo_Helping_Hands.png",
        "alt": "compost image 27"
      },
      {
        "src": "/images/compost/27-1759124179740",
        "alt": "compost image 28"
      },
      {
        "src": "/images/compost/28-site.css",
        "alt": "compost image 29"
      },
      {
        "src": "/images/compost/29-static.css",
        "alt": "compost image 30"
      },
      {
        "src": "/images/compost/30-site-bundle.81624e0f7f7f25a4ec8743ea63cda189.js",
        "alt": "compost image 31"
      }
    ],
    "kaiResilience": [
      {
        "src": "/images/kai-resilience/00-favicon.ico",
        "alt": "kaiResilience image 1"
      },
      {
        "src": "/images/kai-resilience/01-IMG_20240504_143922.jpg",
        "alt": "kaiResilience image 2"
      },
      {
        "src": "/images/kai-resilience/02-IMG_20240504_143922.jpg",
        "alt": "kaiResilience image 3"
      },
      {
        "src": "/images/kai-resilience/03-IMG_20240504_161256.jpg",
        "alt": "kaiResilience image 4"
      },
      {
        "src": "/images/kai-resilience/04-IMG_20240504_161256.jpg",
        "alt": "kaiResilience image 5"
      },
      {
        "src": "/images/kai-resilience/05-IMG_20240504_111546.jpg",
        "alt": "kaiResilience image 6"
      },
      {
        "src": "/images/kai-resilience/06-IMG_20240504_111546.jpg",
        "alt": "kaiResilience image 7"
      },
      {
        "src": "/images/kai-resilience/07-IMG_20240504_104258.jpg",
        "alt": "kaiResilience image 8"
      },
      {
        "src": "/images/kai-resilience/08-IMG_20240504_104258.jpg",
        "alt": "kaiResilience image 9"
      },
      {
        "src": "/images/kai-resilience/09-Untitled_design_-_1.jpg",
        "alt": "kaiResilience image 10"
      },
      {
        "src": "/images/kai-resilience/10-Untitled_design_-_1.jpg",
        "alt": "kaiResilience image 11"
      },
      {
        "src": "/images/kai-resilience/11-Untitled_design_-_2.jpg",
        "alt": "kaiResilience image 12"
      },
      {
        "src": "/images/kai-resilience/12-Untitled_design_-_2.jpg",
        "alt": "kaiResilience image 13"
      },
      {
        "src": "/images/kai-resilience/13-Untitled_design_-_3.jpg",
        "alt": "kaiResilience image 14"
      },
      {
        "src": "/images/kai-resilience/14-Untitled_design_-_3.jpg",
        "alt": "kaiResilience image 15"
      },
      {
        "src": "/images/kai-resilience/15-Health_Post_Logo.png",
        "alt": "kaiResilience image 16"
      },
      {
        "src": "/images/kai-resilience/16-Health_Post_Logo.png",
        "alt": "kaiResilience image 17"
      },
      {
        "src": "/images/kai-resilience/17-Sollys_Logo.png",
        "alt": "kaiResilience image 18"
      },
      {
        "src": "/images/kai-resilience/18-Sollys_Logo.png",
        "alt": "kaiResilience image 19"
      },
      {
        "src": "/images/kai-resilience/19-Logo_TDC.png",
        "alt": "kaiResilience image 20"
      },
      {
        "src": "/images/kai-resilience/20-Logo_TDC.png",
        "alt": "kaiResilience image 21"
      },
      {
        "src": "/images/kai-resilience/21-Logo_Trash_Palace.png",
        "alt": "kaiResilience image 22"
      },
      {
        "src": "/images/kai-resilience/22-Logo_Trash_Palace.png",
        "alt": "kaiResilience image 23"
      },
      {
        "src": "/images/kai-resilience/23-1759124179740",
        "alt": "kaiResilience image 24"
      },
      {
        "src": "/images/kai-resilience/24-site.css",
        "alt": "kaiResilience image 25"
      },
      {
        "src": "/images/kai-resilience/25-static.css",
        "alt": "kaiResilience image 26"
      },
      {
        "src": "/images/kai-resilience/26-site-bundle.81624e0f7f7f25a4ec8743ea63cda189.js",
        "alt": "kaiResilience image 27"
      }
    ],
    "volunteering": [],
    "team": [
      {
        "src": "/images/team/00-favicon.ico",
        "alt": "team image 1"
      },
      {
        "src": "/images/team/01-SLC_gardens_02.png_quot_",
        "alt": "team image 2"
      },
      {
        "src": "/images/team/02-SLC_gardens_02.png",
        "alt": "team image 3"
      },
      {
        "src": "/images/team/03-SLC_gardens_02.png",
        "alt": "team image 4"
      },
      {
        "src": "/images/team/04-IMG-20240222-WA0003_Original.jpeg",
        "alt": "team image 5"
      },
      {
        "src": "/images/team/05-IMG-20240222-WA0003_Original.jpeg",
        "alt": "team image 6"
      },
      {
        "src": "/images/team/06-IMG-20230327-WA0001_Original.jpeg",
        "alt": "team image 7"
      },
      {
        "src": "/images/team/07-IMG-20230327-WA0001_Original.jpeg",
        "alt": "team image 8"
      },
      {
        "src": "/images/team/08-Stef_2.jpg",
        "alt": "team image 9"
      },
      {
        "src": "/images/team/09-Stef_2.jpg",
        "alt": "team image 10"
      },
      {
        "src": "/images/team/10-Max_02.jpg",
        "alt": "team image 11"
      },
      {
        "src": "/images/team/11-Max_02.jpg",
        "alt": "team image 12"
      },
      {
        "src": "/images/team/12-Rosie.jpg",
        "alt": "team image 13"
      },
      {
        "src": "/images/team/13-Rosie.jpg",
        "alt": "team image 14"
      },
      {
        "src": "/images/team/14-Rita.jpg",
        "alt": "team image 15"
      },
      {
        "src": "/images/team/15-Rita.jpg",
        "alt": "team image 16"
      },
      {
        "src": "/images/team/16-Sol.jpg",
        "alt": "team image 17"
      },
      {
        "src": "/images/team/17-Sol.jpg",
        "alt": "team image 18"
      },
      {
        "src": "/images/team/18-Peter.jpg",
        "alt": "team image 19"
      },
      {
        "src": "/images/team/19-Peter.jpg",
        "alt": "team image 20"
      },
      {
        "src": "/images/team/20-Murray_2.jpg",
        "alt": "team image 21"
      },
      {
        "src": "/images/team/21-Murray_2.jpg",
        "alt": "team image 22"
      },
      {
        "src": "/images/team/22-1759124179740",
        "alt": "team image 23"
      },
      {
        "src": "/images/team/23-site.css",
        "alt": "team image 24"
      },
      {
        "src": "/images/team/24-static.css",
        "alt": "team image 25"
      },
      {
        "src": "/images/team/25-site-bundle.81624e0f7f7f25a4ec8743ea63cda189.js",
        "alt": "team image 26"
      }
    ],
    "about": [
      {
        "src": "/images/about/00-favicon.ico",
        "alt": "about image 1"
      },
      {
        "src": "/images/about/01-IMG_2053_Original.jpg",
        "alt": "about image 2"
      },
      {
        "src": "/images/about/02-IMG_2053_Original.jpg",
        "alt": "about image 3"
      },
      {
        "src": "/images/about/03-WhatsApp_Image_2023-06-04_at_16.16.59.jpeg",
        "alt": "about image 4"
      },
      {
        "src": "/images/about/04-WhatsApp_Image_2023-06-04_at_16.16.59.jpeg",
        "alt": "about image 5"
      },
      {
        "src": "/images/about/05-5.png",
        "alt": "about image 6"
      },
      {
        "src": "/images/about/06-5.png",
        "alt": "about image 7"
      },
      {
        "src": "/images/about/07-SLC_info_picture",
        "alt": "about image 8"
      },
      {
        "src": "/images/about/08-SLC_info_picture",
        "alt": "about image 9"
      },
      {
        "src": "/images/about/09-SLC_info",
        "alt": "about image 10"
      },
      {
        "src": "/images/about/10-SLC_info",
        "alt": "about image 11"
      },
      {
        "src": "/images/about/11-beginnings_of_the_hexagon.jpg",
        "alt": "about image 12"
      },
      {
        "src": "/images/about/12-beginnings_of_the_hexagon.jpg",
        "alt": "about image 13"
      },
      {
        "src": "/images/about/13-building_the_earth_building.jpg",
        "alt": "about image 14"
      },
      {
        "src": "/images/about/14-building_the_earth_building.jpg",
        "alt": "about image 15"
      },
      {
        "src": "/images/about/15-No_2.jpg",
        "alt": "about image 16"
      },
      {
        "src": "/images/about/16-No_2.jpg",
        "alt": "about image 17"
      },
      {
        "src": "/images/about/17-No8.jpg",
        "alt": "about image 18"
      },
      {
        "src": "/images/about/18-No8.jpg",
        "alt": "about image 19"
      },
      {
        "src": "/images/about/19-Short_Course_1_.png",
        "alt": "about image 20"
      },
      {
        "src": "/images/about/20-Short_Course_1_.png",
        "alt": "about image 21"
      },
      {
        "src": "/images/about/21-1759124179740",
        "alt": "about image 22"
      },
      {
        "src": "/images/about/22-site.css",
        "alt": "about image 23"
      },
      {
        "src": "/images/about/23-static.css",
        "alt": "about image 24"
      },
      {
        "src": "/images/about/24-site-bundle.81624e0f7f7f25a4ec8743ea63cda189.js",
        "alt": "about image 25"
      }
    ],
    "contact": [
      {
        "src": "/images/contact/00-favicon.ico",
        "alt": "contact image 1"
      },
      {
        "src": "/images/contact/01-picking_food_garden.jpg",
        "alt": "contact image 2"
      },
      {
        "src": "/images/contact/02-picking_food_garden.jpg",
        "alt": "contact image 3"
      },
      {
        "src": "/images/contact/03-1759124179740",
        "alt": "contact image 4"
      },
      {
        "src": "/images/contact/04-site.css",
        "alt": "contact image 5"
      },
      {
        "src": "/images/contact/05-static.css",
        "alt": "contact image 6"
      },
      {
        "src": "/images/contact/06-site-bundle.81624e0f7f7f25a4ec8743ea63cda189.js",
        "alt": "contact image 7"
      }
    ]
  },
  "sponsors": {}
} as const;

export function getPageImages(page: keyof typeof imageManifest.pages): readonly SiteImage[] {
  return imageManifest.pages[page] ?? [];
}
